### ISSUE TITLE
eclint_args causes quotation-explosion

### ISSUE THREAD

**Issue by szepeviktor** [greut/eclint-action#8]
```yml
      - name: "Check adherence to EditorConfig"
        uses: "greut/eclint-action@v0"
        with:
          eclint_args: "-exclude '{bin/generate.php,bin/shape.php}'"
```

Turns into `eclint '-color=always' -exclude ''"'"'{bin/generate.php,bin/shape.php}'"'"`

https://github.com/johnbillion/args/runs/7787549221?check_suite_focus=true

What could it be?

**Comment by szepeviktor** [comment]
This works.

```yaml

      - name: "Check adherence to EditorConfig"
        uses: "greut/eclint-action@v0"
        with:
          eclint_args: "-exclude {bin/generate.php,bin/shape.php}"
```

**Comment by szepeviktor** [comment]
Just found out that using an equal sign makes GHA quote both the option name and its value.

```yaml

      - name: "Check adherence to EditorConfig"
        uses: "greut/eclint-action@v0"
        with:
          eclint_args: |
            -exclude=dependencies/**/*
```

![kép](https://user-images.githubusercontent.com/952007/188214930-456b2609-c723-4278-98a0-d3c4079acec4.png)
